config/routes.rb
Rails.application.routes.draw do

  root				'static_pages#Home'

  get 'about'		=>	'static_pages#About'
  get 'faq'		=>	'static_pages#Faq'
  get 'partners'	=>	'static_pages#Partners'
  get 'pricing'		=>	'static_pages#Pricing'
  get 'contact'		=>	'static_pages#Contact'
  get 'terms'		=>	'static_pages#Terms'
  get 'signup'		=>	'users#new'
  get 'style'		=>	'static_pages#Style'
  get 'style2'		=>	'static_pages#Style2'

  get		'login'		=>	'sessions#new'
  post		'login'		=>	'sessions#create'
  delete	'logout'	=>	'sessions#destroy'

  resources	:users do
    resources	  :members
    resources     :weights
  end
  resources	:account_activations, 	only: [:edit]
  resources	:password_resets,	only: [:new, :create, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :members
  has_many :weights
  
  attr_accessor :remember_token, :activation_token, :reset_token
  geocoded_by :address_line_one
  after_validation :geocode
  before_save :downcase_email
  before_create :create_activation_digest

  # Email Regex
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  ####
  #### VALIDATIONS

  # Name exists and is no longer than 50 characters
  # validates :name, presence: true, length: { maximum: 50 }

  # Email exists, 255 chars or less, is unique, valid, and case insensitive
  validates :email, presence: true, length: { maximum: 255 },
		   format: { with: VALID_EMAIL_REGEX },
		   uniqueness: { case_sensitive: false }

  # Password exists, 72 chars or less, matches password_confirmation, BCrypt password.
  # Ships with methods to set and authenticate agains BCrypt passwords.
  # API: http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html
  has_secure_password

  # Password is no less than 6 characters
  validates :password, length: { minimum: 6 }, allow_blank: true

  ####
  #### SESSION HANDLING

  ## UPDATE TOKENS

  # Set remember_digest in db for validating a permanent cookie
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Delete remember_digest in db
  def forget
    update_attribute(:remember_digest, nil)
  end

  ## READ TOKENS

  # Return true if there is a match of permanent cookie
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  ## GENERATE TOKENS 

  # Returns a hash digest of a given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create( string, cost: cost )
  end

  # Sets password reset attributes
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Returns a random url safe token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Activates an account
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if password reset has expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    def downcase_email 
      self.email = email.downcase 
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  ##
  ## AUTHORIZATION FILTERS

  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :admin_user,	 only: :destroy

  ##
  ## CREATE

  # Create @user object in memory, render new view
  def new
    @user = User.new
  end

  # Accept hash of params from signup form, save user into db
  def create
    @user = User.new(user_params)       # fill @user attributes with hash from form
    if @user.save                       # attempt to save @user into db
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account (email will arrive in a few minutes!)"
      redirect_to root_url
      # log_in @user
      # flash[:success] = "Welcome to Compost App"
      # redirect_to @user
    else                                # if fails, reload the signup page
      render 'new'
    end
  end

  ##
  ## READ

  # Grab user by id and render the users/show view
  # Accessible via example.com/users/:id -- ie. (example.com/users/1)
  def show
    @user = User.find(params[:id])
    @user_weight = Weight.where(user_id: @user.id).sum(:weight)
    @members = @user.members.paginate(page: params[:page])
  end

  # Display users in pagination
  def index
    @users = User.paginate(page: params[:page])
  end

  ##
  ## UPDATE

  # Grad user data to pass along to the edit page
  def edit
    @user = User.find(params[:id])
  end

  # User updates own attributes
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  ##
  ## DESTROY

  # Delete User
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted"
    redirect_to users_url
  end

  private

    # Setup strong parameters for user hash from signup form
    def user_params
      params.require(:user).permit( :email,
				    :password,
				    :password_confirmation,
				    :first_name,
				    :last_name,
				    :address_line_one,
				    :address_line_two )
    end

    # Check if logged in
#    def logged_in_user
#      unless logged_in?
#        store_location			# app/helpers/session_helper.rb
#        flash[:danger] = "Please log in"
#        redirect_to login_url
#      end
#    end

    # Confirms the correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)	# app/helpers/session_helper.rb
    end

    # Checks it current user is an admin
    def admin_user
      redirect_to root_url unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li class="list-group-item">
  <%= link_to user.first_name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" }, class: 'pull-right' %>
  <% end %>
</li>

app/views/users/current_new.html.erb
    <script src="https://checkout.stripe.com/checkout.js"></script>

    <div class="page-header">
        <h2>Sign up<h2>
    </div>
    <div class="form-group well">
	<p><strong>14 day Free Trial</strong></p>
	<p>Currently serving zip codes 76201, 76205, 76207, 76208, 76209, 76210</p>
    </div>

    <!-- Flash Messages -->
    <div class="fade in alert alert-danger">
        <button class="close" data-dismiss="alert">&times;</buttton>
            <div class="strong">
            </div>
    </div>

    <!-- Form Errors -->
    <div id="alerts">
        <div id="emailAlert" class="alert alert-danger" role="alert" style="display: none;">
            <strong>Warning: </strong>A valid e-mail address is required!
        </div>

        <div id="passwordEmptyAlert" class="alert alert-danger" role="alert" style="display: none;">
            <strong>Warning: </strong>Please enter a password
        </div>

        <div id="passwordAlert" class="alert alert-danger" role="alert" style="display: none;">
            <strong>Warning: </strong>Passwords don't match!
        </div>

        <div id="firstNameAlert" class="alert alert-danger" role="alert" style="display: none;">
            <strong>Warning: </strong>A First Name is required!
        </div>

        <div id="lastNameAlert" class="alert alert-danger" role="alert" style="display: none;">
            <strong>Warning: </strong>A Last Name is required!
        </div>

        <div id="addressLineOneAlert" class="alert alert-danger" role="alert" style="display: none;">
            <strong>Warning: </strong>An address is required!
        </div>

        <div id="zipCodeAlert" class="alert alert-info" role="alert" style="display: none;">
            <strong>Warning: </strong>Your Zip Code is not in our service area. We currently service 76201, 76205, 76297, 76208, 76209, 76210. You may consider signing up with our <a href="/newsletter">newsletter</a> to recieve updates about future expansion.
        </div>

        <div id="termsAlert" class="alert alert-danger" role="alert" style="display: none;">
            <strong>Warning: </strong>Please read Terms of Service and check the box.
        </div>

        <div id="genericAlert" class="alert alert-danger" role="alert" style="display: none;">
            <strong>Warning: </strong>Unable to create account :(
        </div>
    </div>

    <!-- BEGIN FORM / BEGIN FORM / BEGIN FORM
    <form id="create-account-form" name="createAccount" action="/users">
        <div class="form-group">
            <label for="email">E-Mail Address</label>
            <input name="email" id="email" class="form-control" type="email" placeholder="(Required)" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input name="password" id="password" class="form-control" type="password", placeholder="(Required)" required>
        </div>
        <div class="form-group">
            <label for="confirm-password">Confirm Password</label>
            <input name="confirm-password" id="confirmPassword" class="form-control" type="password", placeholder="(Required)" required>
        </div>
        <div class="form-group">
            <label for="firstName">First Name</label>
            <input name="firstName" id="firstName" class="form-control" type="text" placeholder="(Required)" required />
        </div>
        <div class="form-group">
            <label for="lastName">Last Name</label>
            <input name="lastName" id="lastName" class="form-control" type="text" placeholder="(Required)" required />
        </div>
        <div class="form-group">
            <label for="addressLineOne">Address Line One</label>
            <input name="addressLineOne" id="addressLineOne" class="form-control" type="text" placeholder="(Required)" required />
        </div>
        <div class="form-group">
            <label for="addressLineTwo">Address Line Two</label>
            <input name="addressLineTwo" id="addressLineTwo" class="form-control" type="text" placeholder="" required />
        </div>
        <div class="form-group">
            <label for="zipCode">Zip Code</label>
            <input name="zipCode" id="zipCode" class="form-control" type="number" placeholder="(Required)" ng-minlength="5" required />
        </div>
        <div class="form-group">
            <label for="numberResidents">Number of Residents</label>
            <select name="numberResidents" id="numberResidents" class="form-control"required>
                <option value='1' selected>1</option>
                <option value='2'>2</option>
                <option value='3'>3</option>
                <option value='4'>4</option>
                <option value='5'>5</option>
                <option value='6'>6</option>
		<option value='7'>7+</option>
            </select>
        </div>
	<div class="form-group well">
	    <label for="terms_of_service">Terms of Service Agreement</label><br>
	    <input type="checkbox" name="terms_of_service" id="terms_of_service" value="true"> I have read and agree to the <a target="_blank" href="/#!/terms">Terms of Service</a>, including a 3 month minimum membership.
	</div>

        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-mobile">
                        <button id="stripeButton" class="btn btn-md btn-success" type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Getting payment..." data-complete-text="<i class='fa fa-check'></i> Success!">
                            <i class="fa fa-usd"></i>
                            Become a Member! 
                        </button>
                    </div>
                </div>
                <div class='col-md-6'>
                    <div class="btn-mobile">
                        <button id="signupSubmit" class="pull-right btn btn-md btn-primary" type="submit" style="display: none;">
                            <span>Submit</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    END FORM / END FORM / END FORM -->

    <!--<div class="row col-md-13">
        <div class="well">
            <strong>Pricing Info:</strong>
            <br />
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <strong>Testing Info:</strong>
            <br />
            <p>
                <b>Card: </b>4242 4242 4242 4242
                <br />
                <b>CVC: </b>123
                <br />
                <b>Expiration: </b>Any date not already passed.
            </p>
        </div>
    </div>-->

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :address_line_one, "Address" %>
      <%= f.text_field :address_line_one, class: 'form-control', id: 'gmaps-input-address' %>

      <%= f.label :address_line_two, "Address (line two)" %>
      <%= f.text_field :address_line_two, class: 'form-control' %>

      <div id='gmaps-error'></div>
      <div class="custom_overlay" onClick="style.pointerEvents='none'"></div>
      <div id='gmaps-canvas'></div>

      <%= f.submit "Save Changes", class: 'btn btn-primary' %>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users list-group">
  <% # For each @user render the _user.html.erb partial %>
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :address_line_one, "Address" %>
      <%= f.text_field :address_line_one, class: 'form-control', id: 'gmaps-input-address' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

    <div id='gmaps-error'></div>
    <div class="well gmaps-canvas-container">
      <div class="custom_overlay" onClick="style.pointerEvents='none'"></div>
      <div id='gmaps-canvas'></div>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<% provide( :title, 'Profile' ) %>
<div class="row">
  <div class="col-md-12">
  <h1><%= @user.first_name %> <%= @user.last_name %></h1>
  <ul class="list-group" id="profile_stats">
    <li class="list-group-item">
      <h3>Total Diversion<span class="pull-right"><strong><%= number_with_delimiter(@user_weight, :delimiter => ',') %></strong> lbs</span></h3>
    </li>
    <li class="list-group-item">
      <h3>Monthly Average<span class="pull-right">coming soon!</span></h3>
    </li>
    <li class="list-group-item">
      <h3>Weekly Average<span class="pull-right">coming soon!</span></h3>
    </li>
  </ul>
  <%= link_to "Log weight", user_members_path(@user), class: "btn btn-primary btn-lg" %>
  <%= link_to "Add member", new_user_member_path(@user), class: "btn btn-default btn-lg"  %>
  </div>
</div>