config/routes.rb
Rails.application.routes.draw do

  root				'static_pages#Home'

  get 'about'		=>	'static_pages#About'
  get 'faq'		=>	'static_pages#Faq'
  get 'partners'	=>	'static_pages#Partners'
  get 'pricing'		=>	'static_pages#Pricing'
  get 'contact'		=>	'static_pages#Contact'
  get 'terms'		=>	'static_pages#Terms'
  get 'signup'		=>	'users#new'
  get 'style'		=>	'static_pages#Style'
  get 'style2'		=>	'static_pages#Style2'

  get		'login'		=>	'sessions#new'
  post		'login'		=>	'sessions#create'
  delete	'logout'	=>	'sessions#destroy'

  resources	:users do
    resources	  :members
    resources     :weights
  end
  resources	:account_activations, 	only: [:edit]
  resources	:password_resets,	only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <hr>
  <p class="pull-right">Feed the soil. Sustain the Future.</p>
  <p>Compost App is <%= link_to 'open source', 'https://github.com/andrewjm/compost-app' %></p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "Compost App", root_path, id: "logo", class: "pull-left" %>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <nav class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
	<% if logged_in? %>
	  <% if admin? %>
            <li><%= link_to "Users", users_path %></li>
	  <% end %>
	  <li><%= link_to "Profile", current_user %></li>
	  <li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
	    <ul class="dropdown-menu">
	      <li><%= link_to "Profile", current_user %></li>
	      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	      <li class="divider"></li>
	      <li><%= link_to "Log out", logout_path, method: "delete"  %></li>
	    </ul>
	  </li>
	<% else %>
	  <li><%= link_to "Log in", login_path  %></li>
          <li><%= link_to "Create account", signup_path  %></li>
	<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0"/>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container content">
      <%-#add flash messages sitewide-%>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>