config/routes.rb
Rails.application.routes.draw do

  root				'static_pages#Home'

  get 'about'		=>	'static_pages#About'
  get 'faq'		=>	'static_pages#Faq'
  get 'partners'	=>	'static_pages#Partners'
  get 'pricing'		=>	'static_pages#Pricing'
  get 'contact'		=>	'static_pages#Contact'
  get 'terms'		=>	'static_pages#Terms'
  get 'signup'		=>	'users#new'
  get 'style'		=>	'static_pages#Style'
  get 'style2'		=>	'static_pages#Style2'

  get		'login'		=>	'sessions#new'
  post		'login'		=>	'sessions#create'
  delete	'logout'	=>	'sessions#destroy'

  resources	:users do
    resources	  :members
    resources     :weights
  end
  resources	:account_activations, 	only: [:edit]
  resources	:password_resets,	only: [:new, :create, :edit, :update]

end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :user
  has_many :weights
  validates :user_id, presence: true
  geocoded_by :address_line_one
  after_validation :geocode
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # THESE NEED SOME WORK BEFORE THEY CAN BE UNCOMMENTED!!!
  before_action :logged_in_user, only: [:create, :index, :show]
  before_action :correct_user, only: [:index, :show]

  # Display members in pagination
  def index
    @user = User.find(params[:user_id])
    @lat = cookies[:latitudine].nil? ? '0.00' : cookies[:latitudine]
    @long = cookies[:longitudine].nil? ? '0.00' : cookies[:longitudine]
    @members = @user.members.paginate(page: params[:page])

    # If no members, set flash and exit
    if @members.empty?
      flash.now[:info] = "Create your first member by clicking the 'Add Member' button!"
      return
    end

    # Check for 'order' param in url
    if params[:order]
      if params[:order] == 'first'
        # Order by first name
        @members = @user.members.order("LOWER(first\_name) asc").paginate(page: params[:page])
      elsif params[:order] == 'last'
        # Order by last name
        @members = @user.members.order("LOWER(last\_name) asc").paginate(page: params[:page])
      elsif params[:order] == 'locale'
        # Order by location
        @members = @user.members.near([@lat, @long], 50).paginate(page: params[:page])
        if @members.empty?
          flash.now[:info] = "No members within 50 miles of your current location. Try ordering by first or last name!"
        end
      end
    else
      # If no 'order' param, default to order by location
      @members = @user.members.near([@lat, @long], 50).paginate(page: params[:page])
      if @members.empty?
        flash.now[:info] = "No members within 50 miles of your current location. Try ordering by first or last name!"
      end
    end
  end

  # Member profile
  def show
    @member = Member.find(params[:id])
  end

  # Make new member
  def new
  end

  def create
    @member = current_user.members.build(member_params)
    if @member.save
      flash[:success] = "Member '#{@member.first_name} #{@member.last_name}' created!"
      redirect_to @current_user
    end
  end

  private

    def member_params
      params.require(:member).permit(:first_name, :last_name, :address_line_one, :address_line_two)
    end

    # Confirms the correct user
    def correct_user
      @user = User.find(params[:user_id])
      redirect_to root_url unless current_user?(@user)  # app/helpers/session_helper.rb
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_member.html.erb
<% if member.address_line_two.present? %>
  <li class="member-list-item-tall list-group-item">
    <h4 ><strong><%= member.first_name %> <%= member.last_name %></strong></h4>
    <%= truncate(member.address_line_one, :length => 35) %>
    <br>
    <%= truncate(member.address_line_two, :length => 35) %>
    <%= link_to user_member_path(id: member.id, user_id: @user.id), class: 'member-profile-link pull-right' do %>
      Profile <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <% end %>
  </li>
<% else %>
  <li class="member-list-item list-group-item">
    <h4 ><strong><%= member.first_name %> <%= member.last_name %></strong></h4>
    <%= truncate(member.address_line_one, :length => 35) %>
    <%= link_to user_member_path(id: member.id, user_id: @user.id), class: 'member-profile-link pull-right' do %>
      Profile <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <% end %>
  </li>
<% end %>

app/views/members/index.html.erb
<% provide(:title, "Sort Members") %>
<h1>Sort Members</h1>

<div class="btn-group btn-group-justified" id="member_order_buttons" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-lg" id="btn-first"><span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true"></span> First Name</button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-lg" id="btn-last"><span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true"></span> Last Name</button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-lg" id="btn-locale"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Location</button>
  </div>
</div>

<ul class="users list-group">
  <% # For each @member render the _member.html.erb partial %>
  <% @members.each do |member| %>
    <%= render member %>
  <% end %>
</ul>

<%= will_paginate %>

<%= link_to "Add member", new_user_member_path(@user), class: "btn btn-primary btn-lg"  %>

app/views/members/new.html.erb
<% provide(:title, 'Add member') %>
<h1>Add member</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:user, Member.new]) do |f| %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :address_line_one, "Address" %>
      <%= f.text_field :address_line_one, class: 'form-control', id: 'gmaps-input-address' %>

      <%= f.label :address_line_two, "Address line two (optional)" %>
      <%= f.text_field :address_line_two, class: 'form-control' %>

      <%= f.submit "Create member", class: "btn btn-primary" %>
    <% end %>

    <div id='gmaps-error'></div>
    <div class="well gmaps-canvas-container">
      <div class="custom_overlay" onClick="style.pointerEvents='none'"></div>
      <div id='gmaps-canvas'></div>
    </div>

  </div>
</div>

app/views/members/show.html.erb
<% provide( :title, @member.first_name ) %>
<div class="row">
  <aside class="col-md-4">
    <h1><%= @member.first_name %> <%= @member.last_name %></h1>
    <h4><%= @member.address_line_one %></h4>
    <% if @member.address_line_two.present? %>
      <h4><%= @member.address_line_two %></h4>
    <% end %>
    <h4><strong><%= @member.weights.sum(:weight) %></strong> lbs collected</h4>
  </aside>
  <div class="col-md-8">
    <ol class="users list-group">
      <% # For each @member render the _member.html.erb partial %>
      <!-- could list weight logs here -->
    </ol>

    <%= form_for([:user, Weight.new]) do |f| %>

      <%= f.hidden_field :member_id, :value => @member.id %>

      <%= f.label :weight %>
      <div class="input-group input-group-lg">
        <%= f.number_field :weight, class: 'form-control', id: 'weight_log_input' %>
        <span class="input-group-addon" id="basic-addon">lbs</span>
        <span class="input-group-btn">
          <%= f.submit "Log weight", class: "btn btn-primary" %>
        </span>
      </div>

    <% end %>

    <div class="weight-log-buttons btn-group btn-group-justified" id="weight_buttons" role="group" aria-label="...">
      <div class="btn-group btn-group-lg" role="group">
        <button type="button" class="btn btn-success" id="+50">+50</button>
      </div>
      <div class="btn-group btn-group-lg" role="group">
        <button type="button" class="btn btn-success" id="+10">+10</button>
      </div>
      <div class="btn-group btn-group-lg" role="group">
        <button type="button" class="btn btn-success" id="+5">+5</button>
      </div>
      <div class="btn-group btn-group-lg" role="group">
        <button type="button" class="btn btn-success" id="+1">+1</button>
      </div>
    </div>

    <div class="weight-log-buttons btn-group btn-group-justified" role="group" aria-label="...">
      <div class="btn-group btn-group-lg" role="group">
        <button type="button" class="btn btn-danger" id="-50">-50</button>
      </div>
      <div class="btn-group btn-group-lg" role="group">
        <button type="button" class="btn btn-danger" id="-10">-10</button>
      </div>
      <div class="btn-group btn-group-lg" role="group">
        <button type="button" class="btn btn-danger" id="-5">-5</button>
      </div>
      <div class="btn-group btn-group-lg" role="group">
        <button type="button" class="btn btn-danger" id="-1">-1</button>
      </div>
    </div>

  </div>
</div>